# Generated by Django 3.2.7 on 2021-12-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_auto_20211203_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carRegistrationNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cityRegistration', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('equipment', models.CharField(choices=[('PU', 'Pick Up'), ('T', 'Con Trunk'), ('NT', 'Sin Trunk')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=40)),
                ('documentNumber', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
                ('lastName', models.CharField(max_length=60, null=True)),
                ('birthDate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=40, null=True)),
                ('documentNumber', models.CharField(max_length=20, null=True)),
                ('licenseNumber', models.CharField(max_length=20, null=True)),
                ('phoneNumber', models.CharField(max_length=60, null=True)),
                ('carRegistrationNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_driver', to='AuthApp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
