# Generated by Django 3.2.7 on 2021-12-03 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_car_driver_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='carRegistrationNumber',
            new_name='car',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='id',
            field=models.BigAutoField(default=111, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='car',
            name='carRegistrationNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='birthDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='birthDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
