# Generated by Django 3.2.7 on 2021-12-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_auto_20211203_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
