# Generated by Django 3.2.7 on 2021-12-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0006_alter_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='carRegistrationNumber',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
